apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
  labels:
    {{- include "hello-world-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}  # 容器的实际监听端口 (5000)
      nodePort: {{ .Values.service.nodePort }}    # NodePort 外部暴露端口 (30001)
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world-chart.selectorLabels" . | nindent 4 }}
